### ISSUE TITLE
How can I  analyse my  container data which I get from collector?

### ISSUE THREAD

**Issue by Dracula-36** [banyanops/collector#13]
You mentioned that "For further details about how one might use this in an enterprise, please check out [Banyan](http://www.banyanops.com). This SAAS service offers deeper analysis of your data and provides a dashboard showing which of your images are compliant to your policies (e.g., which of your images have security vulnerabilities, etc.) along with real-time updates and email notifications. " in README.md.But I browsed [Banyan](http://www.banyanops.com), and I can't find the way for deeper analysis.Or where is the SAAS you mentioned in README.md?
(Sorry,my English is not good)

**Comment by yoshiotu** [comment]
Thank you for your question. The analysis service is in private beta. The web page lets you submit your contact information if you would like to participate.

**Comment by Dracula-36** [comment]
Thank you for your reply.I'd like to participate and I have sent reply to your email.I'm looking forward to your help.
