### ISSUE TITLE
Collect from local images

### ISSUE THREAD

**Issue by yoshiotu** [banyanops/collector#15]
It would be useful to add a mode that would allow Collector to detect and gather information from local images on a Docker host instead of having to pull from a registry.

**Comment by Dracula-36** [comment]
How?

**Comment by yoshiotu** [comment]
The idea is that Collector would run on a Docker host where images are being built/committed. Instead of detecting new images by querying a remote registry and processing the new images by "docker pull"ing them, Collector would only need to query or hook into the local docker daemon to detect new image builds on the host, and there's no need for "docker pull" because the detected images are already local.

**Comment by yoshiotu** [comment]
Thanks for this awesome code contribution, @gitmej !
