### ISSUE TITLE
Docker version 17.03.0-ce broke collector

### ISSUE THREAD

**Issue by jg8481it** [banyanops/collector#28]
After updating Docker on my Macbook to version 17.03.0-ce, I am now getting the following error. 

```
[19:05:34 2017/03/19 -0400] [EROR] (except.Error:16) strconv.ParseInt: parsing "0-ce": invalid syntax
[19:05:34 2017/03/19 -0400] [EROR] (except.Fail:18) Could not determine Docker version
```

**Comment by yoshiotu** [comment]
Thanks. Fixed in 60864537f9b8046d1b42258756e36a54149dddf9

**Comment by jg8481it** [comment]
Thank you yoshiotu. I will test this today, and if it's working on my end I will close this.

**Comment by jg8481it** [comment]
After updating to the latest version of collector, the issue is now gone on my Macbook. Thank you for the assistance.
